

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TropicTrail
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;


public partial class TropicTrailEntities : DbContext
{
    public TropicTrailEntities()
        : base("name=TropicTrailEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<Reservation> Reservation { get; set; }

    public DbSet<Role> Role { get; set; }

    public DbSet<Services> Services { get; set; }

    public DbSet<Tour_Type> Tour_Type { get; set; }

    public DbSet<User> User { get; set; }

    public DbSet<UserRole> UserRole { get; set; }

    public virtual ObjectResult<sp_Service_Result> sp_Service(Nullable<int> id)
    {

        var idParameter = id.HasValue ?
            new ObjectParameter("id", id) :
            new ObjectParameter("id", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Service_Result>("sp_Service", idParameter);
    }

}

}

