//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TropicTrail
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int reservation_Id { get; set; }
        public Nullable<System.DateTime> date_In { get; set; }
        public Nullable<System.DateTime> date_Out { get; set; }
        public Nullable<int> service_Id { get; set; }
        public Nullable<int> booked_By { get; set; }
        public string payment { get; set; }
        public string status { get; set; }
    
        public virtual Services Services { get; set; }
        public virtual User User { get; set; }
    }
}
