//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TropicTrail
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services
    {
        public Services()
        {
            this.Reservation = new HashSet<Reservation>();
        }
    
        public int service_Id { get; set; }
        public Nullable<int> tourType_Id { get; set; }
        public string service_Description { get; set; }
        public string max_Guest { get; set; }
        public string service_Price { get; set; }
    
        public virtual ICollection<Reservation> Reservation { get; set; }
        public virtual Tour_Type Tour_Type { get; set; }
    }
}
